# CIFAR-100 / ResNet-18
experiment_name: cv_resnet18_cifar100

seed: 42
seeds: [42, 43, 44]
deterministic: true
amp: true

paths:
  data_root: ./data
  out_dir: ./runs/cv_resnet18_cifar100

dataset:
  name: cifar100
  num_classes: 100
  image_size: 32
  train_split: train
  val_split: test
  normalize: true
  augment:
    random_crop: true
    crop_padding: 4
    random_horizontal_flip: true
  num_workers: 8
  pin_memory: true

model:
  family: resnet
  arch: resnet18
  pretrained: false
  residual_aware: true
  expose_units: conv_channels
  prune_residual_branch_only: true

train:
  epochs: 15
  batch_size: 128
  eval_batch_size: 256
  optimizer: sgd
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9
  nesterov: true
  lr_schedule: cosine
  warmup_epochs: 0

score:
  methods: [gndi, magnitude, snip, grasp, synflow, hrank]
  gndi: { p_norm: 2, baseline: zero, max_batches: 8, use_cached_activations: true }
  magnitude: { norm: l1 }
  snip: { at_init: false, max_batches: 2 }
  grasp: { max_batches: 2 }
  synflow: { data_free: true }
  hrank: { max_batches: 8 }
  warmup_epochs: 1

causal_ground_truth:
  enabled: true
  units_to_sample: 400
  metric: output_delta
  p_norm: 2
  batches: 4

prune:
  granularity: unit
  unit_kind: conv_channels
  global_ranking: true
  budget_type: params
  budgets: [0.01, 0.02, 0.05, 0.10, 0.20, 0.30, 0.50]
  per_layer_cap: 0.5
  structural: false

finetune:
  enabled: true
  epochs: 3
  batch_size: 128
  lr: 0.03
  weight_decay: 0.0005
  momentum: 0.9
  lr_schedule: cosine

eval:
  topk: [1]
  metrics: [accuracy, flops, params]
  bootstrap:
    spearman: { rounds: 1000, ci: 0.95 }

report:
  save_json: true
  save_csv: true
  save_plots: true
  build_pdf: true
